on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  dotnet-format-all:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        dotnet-format:
          - 3.1.37601
          - 3.2.107702
          - 3.3.111304
    runs-on: ${{ matrix.os }}
    steps:
      - id: meta
        shell: bash
        run: |
          _version="$(echo "${{ matrix.dotnet-format }}" | cut -c 1)"
          echo "::set-output name=version::${_version}"
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "3.1.x"
      - run: dotnet --info
      - uses: xt0rted/dotnet-format-problem-matcher@preview
        with:
          use-workspace: true
      - run: dotnet tool install --global dotnet-format --version ${{ matrix.dotnet-format }}
      - uses: xt0rted/dotnet-format@preview
        if: always()
        with:
          version: ${{ steps.meta.outputs.version }}
          verbosity: diagnostic
          only-changed-files: false
          workspace: ./2.1
      - uses: xt0rted/dotnet-format@preview
        if: always()
        with:
          version: ${{ steps.meta.outputs.version }}
          verbosity: diagnostic
          only-changed-files: false
          workspace: ./3.1

  dotnet-format-changed:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        dotnet-format:
          - 3.1.37601
          - 3.2.107702
          - 3.3.111304
    runs-on: ${{ matrix.os }}
    steps:
      - id: meta
        shell: bash
        run: |
          _version="$(echo "${{ matrix.dotnet-format }}" | cut -c 1)"
          echo "::set-output name=version::${_version}"
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "3.1.x"
      - run: dotnet --info
      - uses: xt0rted/dotnet-format-problem-matcher@preview
        with:
          use-workspace: true
      - run: dotnet tool install --global dotnet-format --version ${{ matrix.dotnet-format }}
      - uses: xt0rted/dotnet-format@preview
        if: always()
        with:
          version: ${{ steps.meta.outputs.version }}
          verbosity: diagnostic
          only-changed-files: true
          workspace: ./2.1
      - uses: xt0rted/dotnet-format@preview
        if: always()
        with:
          version: ${{ steps.meta.outputs.version }}
          verbosity: diagnostic
          only-changed-files: true
          workspace: ./3.1
